[pytest]
pythonpath = .
asyncio_mode = auto
testpaths = src/tests

filterwarnings =
    # Игнорируем устаревший crypt в passlib
    ignore:'crypt' is deprecated:DeprecationWarning
    # Игнорируем версию argon2
    ignore:Accessing argon2\.__version__ is deprecated:DeprecationWarning
    # Игнорируем utcnow в pydantic/sqlmodel
    ignore:datetime.datetime.utcnow\(\) is deprecated:DeprecationWarning
    # Игнорируем предупреждение про event_loop
    ignore:The event_loop fixture provided by pytest-asyncio has been redefined:DeprecationWarning
